#  _____  _____   _____    _____ _    _  ____  _____
# |  __ \|  __ \ / ____|  / ____| |  | |/ __ \|  __ \
# | |__) | |__) | |  __  | (___ | |__| | |  | | |__) |
# |  _  /|  ___/| | |_ |  \___ \|  __  | |  | |  ___/
# | | \ \| |    | |__| |  ____) | |  | | |__| | |
# |_|  \_\_|     \_____| |_____/|_|  |_|\____/|_|
#
# Here is RPGSHOP config file.

# The language for this plugin.
# String (possible values: "zh_cn", "en_us")
language: zh_cn